version: '3.8'

services:
  clickflow-api:
    container_name: clickflow-api
    image: clickflow-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7087:7087"
    environment:
      ASPNETCORE_ENVIRONMENT: "Production"

      # Connection String
      ConnectionStrings__ClickFlowDB: "Server=clickflow-db.cpimum0agr0p.ap-southeast-1.rds.amazonaws.com;database=ClickFlowDB;uid=admin;pwd=Clickflow123987;Trust Server Certificate=True;"

      # CORS
      Cors__AllowedOrigins__0: "https://clickflow88.vercel.app"
      Cors__AllowedOrigins__1: "http://localhost:3000"

      # JWT
      JWT__ValidAudience: "http://localhost:8099"
      JWT__ValidIssuer: "http://localhost:8099"
      JWT__Secret: "VGhpcyBpcyBhIHZlcnkgbG9uZyBhbmQgc2VjdXJlIHNlY3JldCBrZXkgdGhhdCBtZWV0cyB0aGUgbGVuZ3RoIHJlcXVpcmVtZW50Lg=="

      # VNPAY
      VnPayConfiguration__ReturnUrl: "https://clickflowapi.site/api/Transactions/response-payment"
      VnPayConfiguration__PaymentUrl: "https://sandbox.vnpayment.vn/paymentv2/vpcpay.html"
      VnPayConfiguration__TmnCode: "I8PLQV6H"
      VnPayConfiguration__HashSecret: "DFQXQ0Z6X0EPQ97P656V0UJWIGXPFS2Z"
      VnPayConfiguration__Version: "2.1.0"
      VnPayConfiguration__Command: "pay"
      VnPayConfiguration__CurrCode: "VND"
      VnPayConfiguration__Locale: "vn"

      # Email
      EmailConfiguration__From: "nguyenkhaiqui2003@gmail.com"
      EmailConfiguration__SmtpServer: "smtp.gmail.com"
      EmailConfiguration__Port: 465
      EmailConfiguration__UserName: "nguyenkhaiqui2003@gmail.com"
      EmailConfiguration__Password: "zjft iyxn dypm kiyw"

      # Cloudinary
      Cloudinary__CloudName: "detykxgzs"
      Cloudinary__ApiKey: "514788938548365"
      Cloudinary__ApiSecret: "CaFoysPdKo78rk9dv1q74f2sLxc"

      # Admin
      Admin__email: "nguyenkhaiqui2003@gmail.com"
      Admin__password: "ThisIsAdmin123456@"

      # Pusher
      PusherConfiguration__AppId: "2000246"
      PusherConfiguration__Key: "a0aa42bd68a3276e08b2"
      PusherConfiguration__Secret: "cbea6dd03b34336acbb5"
      PusherConfiguration__Cluster: "ap1"

      # PayOS
      PayOS__ClientId: "8729d130-4c61-433d-bc71-34d6ea50b271"
      PayOS__ApiKey: "313792b4-eacc-41ac-a360-a5dc43fa4fde"
      PayOS__ChecksumKey: "76018a47421344d20050ca89f5f69367ffcf2c032631aa41b70f424c4f7729c7"

      # Google Auth
      Authentication__Google__ClientId: "965896936969-co9t7unlhu185gf2j00hhb427386oc6m.apps.googleusercontent.com"

      # Frontend URL
      FronendURL: "https://clickflow88.vercel.app"

    restart: unless-stopped
