version: '3.8'

services:
  clickflow-api:
    container_name: clickflow-api
    image: clickflow-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7087:7087"
    environment:
      ASPNETCORE_ENVIRONMENT: "Production"

    restart: unless-stopped
